require('dotenv').config();
const bcrypt = require('bcryptjs');
const mongoose = require('mongoose');
const connectDB = require('./config/dbconnect');
const User = require('./models/user');
const Client = require('./models/client');
const Invoice = require('./models/invoice');
const Settings = require('./models/settings');

const runSeed = async () => {
  if (!process.env.MONGODB_URI) {
    throw new Error('MONGODB_URI is not defined');
  }

  await connectDB();

  await Promise.all([
    Invoice.deleteMany({}),
    Client.deleteMany({}),
    Settings.deleteMany({}),
    User.deleteMany({}),
  ]);

  const password = await bcrypt.hash('Password123!', 10);

  const user = await User.create({
    name: 'Quick Bill Demo',
    email: 'demo@quickbill.com',
    password,
    phone: '+212600000000',
    isVerified: true,
  });

  const settings = await Settings.create({
    user: user._id,
    companyName: 'Quick Bill Studio',
    companyAddress: '12 Atlas Street, Casablanca',
    companyICE: 'ICE-12345678',
    vatEnabled: true,
    vatRate: 0.2,
    currency: 'DH',
    numberingPrefix: 'INV',
    zeroPadding: 4,
    resetNumberYearly: true,
    businessType: 'services',
    monthlyCap: 200000,
  });

  user.settings = settings._id;

  const clients = await Client.insertMany([
    {
      userId: user._id,
      name: 'Atlas Consulting SARL',
      address: '45 Hassan II Blvd, Rabat',
      ice: 'ICE-ATL-001',
    },
    {
      userId: user._id,
      name: 'Northwind Retail',
      address: '8 Ocean Avenue, Tangier',
      ice: 'ICE-NW-002',
    },
  ]);

  const now = new Date();
  const daysAgo = (days) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
  const daysFromNow = (days) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

  const invoiceSeedData = [
    {
      number: 'INV-0001',
      client: clients[0],
      status: 'paid',
      date: daysAgo(28),
      dueDate: daysAgo(18),
      items: [{ description: 'Brand identity workshop', quantity: 1, unitPrice: 3000 }],
    },
    {
      number: 'INV-0002',
      client: clients[0],
      status: 'paid',
      date: daysAgo(22),
      dueDate: daysAgo(12),
      items: [
        { description: 'Landing page design', quantity: 1, unitPrice: 4200 },
        { description: 'Copywriting', quantity: 1, unitPrice: 1500 },
      ],
    },
    {
      number: 'INV-0003',
      client: clients[1],
      status: 'paid',
      date: daysAgo(20),
      dueDate: daysAgo(10),
      items: [{ description: 'Monthly bookkeeping', quantity: 1, unitPrice: 1800 }],
    },
    {
      number: 'INV-0004',
      client: clients[1],
      status: 'pending',
      date: daysAgo(6),
      dueDate: daysFromNow(8),
      items: [
        { description: 'Website maintenance', quantity: 1, unitPrice: 2400 },
        { description: 'Support retainer', quantity: 1, unitPrice: 1200 },
      ],
    },
    {
      number: 'INV-0005',
      client: clients[0],
      status: 'pending',
      date: daysAgo(3),
      dueDate: daysFromNow(12),
      items: [{ description: 'SEO audit', quantity: 1, unitPrice: 3500 }],
    },
    {
      number: 'INV-0006',
      client: clients[0],
      status: 'overdue',
      date: daysAgo(24),
      dueDate: daysAgo(4),
      items: [{ description: 'Social media campaign', quantity: 1, unitPrice: 5000 }],
    },
    {
      number: 'INV-0007',
      client: clients[1],
      status: 'overdue',
      date: daysAgo(17),
      dueDate: daysAgo(2),
      items: [
        { description: 'Product photography', quantity: 1, unitPrice: 2800 },
        { description: 'Image retouching', quantity: 4, unitPrice: 250 },
      ],
    },
  ];

  const invoices = invoiceSeedData.map((entry) => {
    const subtotal = entry.items.reduce((total, item) => total + item.quantity * item.unitPrice, 0);
    const vat = Math.round(subtotal * 0.2 * 100) / 100;

    return {
      userId: user._id,
      number: entry.number,
      date: entry.date,
      dueDate: entry.dueDate,
      clientName: entry.client.name,
      clientAddress: entry.client.address,
      clientICE: entry.client.ice,
      status: entry.status,
      items: entry.items,
      subtotal,
      vat,
      total: subtotal + vat,
      notes: 'Sample invoice generated by the seed script.',
    };
  });

  const createdInvoices = await Invoice.insertMany(invoices);

  user.invoices = createdInvoices.map((invoice) => invoice._id);
  await user.save();

  console.log('Seed complete');
  console.log(`User: ${user.email}`);
  console.log('Password: Password123!');
  console.log(`Clients created: ${clients.length}`);
  console.log(`Invoices created: ${createdInvoices.length}`);
};

runSeed()
  .catch((error) => {
    console.error('Seed failed:', error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.disconnect();
  });